export enum AccountAccess {
  ALLOWED_THIRD_PARTY, ALLOWED_SADAD, ALLOWED_VISA_PAYMENT, ALLOWED_TRANSFER_TO, ALLOWED_PAYMENTS, ALLOWED_VISA_CASH_ADVANCE, ALLOWED_TRANSFERS, ALLOWED_TRANSFER_FROM, ALLOWED_SUMMARY, ALLOWED_ACCOUNT_TRANSACTIONS, ALLOWED_CBR, ALLOWED_DEBITCARD_LINK, ALLOWED_SHOW_BALANCE, ALLOWED_ADDITIONAL_ACCOUNT, ALLOWED_STATEMENT_BY_MAIL, ALLOWED_REPORT_LOST_CHEQUE, NONE
}
